# [config.rs](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/config.rs)
# [rustfmt-configs-guide](https://github.com/regexident/rustfmt-configs-guide)
max_width = 100
newline_style = "Unix"
reorder_imports = true
