[package]
name = "traits"
version = "0.1.0"
authors = ["fstnetwork <admin@fstk.io>"]

[dependencies]
types = { path = "../types" }

ethcore-transaction = { git = "https://github.com/paritytech/parity-ethereum.git" }

ethereum-types = "0.4.0"
futures = "0.1.25"
bytes = "0.4.11"
